lang_model:
    balancer_config:
        # Min priority value = 100
        server_choices:
            local_host:
                priority: 10
                url: 'http://localhost:5000/v1/completions'
            remote_host:
                priority: 20
                url: 'https://ai.sweetie.bot/llm/v1/completions'
        fallback_answer: 'angry | Sweetie Bot: Error! Connection to the brain has been lost!'
    profile:
        en:
            max_tokens: 250
            do_sample: True
            temperature: 1.3
            top_p: 0.1
            typical_p: 1
            repetition_penalty: 1.18
            top_k: 40
            no_repeat_ngram_size: 0
            penalty_alpha: 0
            seed: -1
            add_bos_token: True
            truncation_length: 2048
            ban_eos_token: False
            skip_special_tokens: True
            stop: ["\nMy emotion:", "\nHuman:", "\n"]
        ru:
            max_tokens: 250
            do_sample: True
            temperature: 1.3
            top_p: 0.1
            typical_p: 1
            repetition_penalty: 1.18
            top_k: 40
            no_repeat_ngram_size: 0
            penalty_alpha: 0
            seed: -1
            add_bos_token: True
            truncation_length: 2048
            ban_eos_token: False
            skip_special_tokens: True
            stop: ["\nМои эмоции:", "\nЧеловек:", "\n"]
        ja:
            max_tokens: 250
            do_sample: True
            temperature: 1.3
            top_p: 0.1
            typical_p: 1
            repetition_penalty: 1.18
            top_k: 40
            no_repeat_ngram_size: 0
            penalty_alpha: 0
            seed: -1
            add_bos_token: True
            truncation_length: 2048
            ban_eos_token: False
            skip_special_tokens: True
            stop: ["\n私の感情：", "\n人間：", "\n"]

classification_model:
    balancer_config:
        # Min priority value = 100
        server_choices:
            local_host:
                priority: 10
                url: 'http://localhost:5011/'
            remote_host:
                priority: 20
                url: 'https://ai.sweetie.bot/classification/'

transcriber:
    balancer_config:
        # Min priority value = 100
        server_choices:
            local_host:
                priority: 10
                url: 'http://localhost:8577/'
            remote_host:
                priority: 20
                url: 'https://ai.sweetie.bot/stt/'

translator:
    balancer_config:
        # Min priority value = 100
        server_choices:
            local_host:
                priority: 10
                url: 'http://127.0.0.1:5001/translate'
            remote_host:
                priority: 20
                url: 'https://ai.sweetie.bot/trans/'