joint_state_ref:
    num_rows: 7
dynamics_visualizer:
    robot_model_namespace: "/motion"
    display_twist: true
stance_pose_marker:
    normalized_z_level: 0.03
    scale: 1.5
    resources: [leg1, leg2, leg3, leg4 ]
    frames: [ base_link, leg1_link6, leg2_link6, leg3_link6, leg4_link6, head_link5 ]
    marker_home_frame: base_link
    normalized_z_level: 0.2335
limb_pose_marker:
    normalized_z_level: 0.03
    scale: 0.75
    resources: [leg1, leg2, leg3, leg4, head, nose ]
    frames: [ base_link, leg1_link6, leg2_link6, leg3_link6, leg4_link6, head_link4, head_link5 ]
head_target_marker:
    normalized_z_level: 0.35
    scale: 0.3
    resources: [ head ]
    frames: [ ]
robot_pose_marker:
    name: "Stance Pose marker"
    world_frame: odom_combined
    scale: 1.3
    normalized_z_level: 0.279585
    frame: base_link
    inner_markers:
      legs:
        list:
          leg1: { resource: leg1, frame: leg1_link6, name: "Front-Left leg Pose marker"  }
          leg2: { resource: leg2, frame: leg2_link6, name: "Front-Right leg Pose marker" }
          leg3: { resource: leg3, frame: leg3_link6, name: "Back-Left leg Pose marker"   }
          leg4: { resource: leg4, frame: leg4_link6, name: "Back-Right leg Pose marker"  }
        normalized_z_level: 0.035
        scale: 0.7
      limbs:
        # You can add limb marker by adding another entry in this list.
        # Markers' name fields must be different!!!
        nose:
          name: "Nose Pose marker"
          is_sphere: true
          scale: 0.7
          normalized_z_level: 0.44785
          frame: nose_link2
          resource: nose
          pose_topic: limb_pose
          activation_action: limb_set_operational_action
        head:
          name: "Look At marker"
          is_sphere: true
          scale: 0.5
          normalized_z_level: 0.3287
          frame: nose_link2
          resource: head
          pose_topic: look_at_pose
          activation_action: look_at_set_operational_action
destination_marker:
    name: "Destination Marker"
    world_frame: odom_combined
    scale: 1.3
    gait_type_options: [ walk_overlap, walk, trot ]
    gait_type_default_idx: 0
    n_steps_options: [ 2, 3, 4, 5 ]
    n_steps_default_idx: 2
    duration: 5
    nominal_height: 0.25
    recorded_trajectory_name: "recorded_trajectory"
    ee_names: [ leg1, leg2, leg3, leg4 ]
object_detection_marker:
    names: [ "Detection 1", "Detection 2", "Detection 3" ]
    labels: [ "", "Alex", "Alice", "yes", "no", "greeting", "hand_greeting", "brohoof" ]
    types: [ "human", "pony", "ball", "qr", "hand" ]
    frame: odom_combined
    scale: 0.5
    nominal_height: 0.4
