buttons:
    type: KeyPressed
    joy_topic: "joystick"
    key_topic: "keys_pressed"
    deadzone: 0.1
    enabled_on_start: true
    buttons:
        0: "3"
        1: "2"
        2: "4"
        3: "1"
        4: "L1"
        5: "R1"
        6: "select"
        7: "start"
    axes_positive:
        0: "tumble"
        1: "tumble"
        3: "tumble"
        4: "tumble"
        6: "left"
        7: "up"
    axes_negative:
        0: "tumble"
        1: "tumble"
        3: "tumble"
        4: "tumble"
        5: "R2"
        2: "L2"
        6: "right"
        7: "down"
head:
    type: JointAxes
    joy_topic: "joystick"
    joints_topic: "joints_ref"
    enabled_on_start: false
    buttons: 
        5:
            joint: "head_joint1"
            speed: 0.4
            min: 0.0
            max: 0.8
    axes:
        0:
            joint: "eyes_yaw"
            speed: 0.0
            min: 1.2
            max: -1.2
        1:
            joint: "eyes_pitch"
            speed: 0.0
            min: -1.2
            max: 1.2
        5:
            joint: "head_joint1"
            speed: -0.4
            min: 0.0
            max: 0.8
        4:
            joint: "head_joint2"
            speed: 0.0
            min: -0.3
            max: 0.3
        3:
            joint: "head_joint4"
            speed: 0.0
            min: -0.8
            max: 0.8


