buttons:
    type: KeyPressed
    joy_topic: "joystick"
    key_topic: "keys_pressed"
    buttons:
        0: "1"
        1: "2"
        2: "3"
        3: "4"
        4: "L1"
        6: "L2"
        5: "R1"
        7: "R2"
        8: "select"
        9: "start"
    axes_positive:
        0: "tumble"
        1: "tumble"
        2: "tumble"
        3: "tumble"
        4: "left"
        5: "up"
    axes_negative:
        0: "tumble"
        1: "tumble"
        2: "tumble"
        3: "tumble"
        4: "right"
        5: "down"
eyes: 
    type: JointAxes
    joy_topic: "joystick"
    joints_topic: "eyes_joints_ref"
    buttons: {}
    axes:
        2:
            joint: "eyes_yaw"
            speed: 0.0
            min: -1.2
            max: 1.2
        3:
            joint: "eyes_pitch"
            speed: 0.0
            min: -1.2
            max: 1.2
head:
    type: JointAxes
    joy_topic: "joystick"
    joints_topic: "head_joints_ref"
    buttons:
        5:
            joint: "joint51"
            speed: 0.4
            min: -1.2
            max: 0.2
        7:
            joint: "joint51"
            speed: -0.4
            min: -1.2
            max: 0.1
    axes:
        0:
            joint: "joint52"
            speed: 0.0
            min: 1.0
            max: -1.0
        1:
            joint: "joint53"
            speed: 0.0
            min: -0.1
            max: 0.6


