soar:
    soar_period: 0.5
    autostart: false
    agent_package: "sweetie_bot_soar"
    agent_file: "soar/talker.soar"
    input:
        rand:
            type: "rand"
        clock:
            type: "clock"
        joystick:
            type: "joystick"
            topic: "/hmi/joy_decoder/keys_pressed"
        camera:
            type: "camera"
            timeout: 15
            topic: "detections"
    output:
        nop: true
        textcmd: 
            topic: "control"
        flexbe:
            action_ns: "flexbe/flexbe/execute_behavior"
