vision:
    camera_frame: 'camera_link_optical'
    #camera_matrix: [ 301.042,       0, 343.414,
                         #0, 300.935,  229.03,
                         #0,       0,       1, ]
    camera_matrix: [    375,      0,  400,
                         0,     375,  300,
                         0,       0,    1, ]
    apply_undistortion: true
    distortion_coefficients: [ 0.501383, 0.0370812, -7.27019e-05, -0.000171416, -4.35192e-06, 0.852262, 0.137816, 0.00259195, 0, 0, 0, 0, 0, 0, ]
    #distortion_coefficients: [ -12.7798169242237084e-02, -3.5606715553346212e-04, -1.0833438941311863e-02, 0. ]
    input_stream: 'udpsrc port=5000 ! application/x-rtp, encoding-name=JPEG,payload=26 !  rtpjpegdepay !  jpegdec ! videoconvert ! appsink'
    # Dublicate gstreamer video stream to 5001 port to allow recording.
    #input_stream: "udpsrc port=5000 ! tee name=RecievedStream ! queue ! application/x-rtp, encoding-name=JPEG,payload=26 ! rtpjpegdepay !  jpegdec ! videoconvert ! appsink RecievedStream. ! queue ! udpsink host=127.0.0.1 port=5001"
    # If true node shows a window with resulting detections on the video
    show_video_result: true
    fps_lock: 30
    distance_to_camera: 0.3
    face_recognizer:
        detection_model_xml: "/models/face_detection/FP16/face-detection-retail-0004.xml"
        landmarks_model_xml: "/models/landmarks_regression/FP16/landmarks-regression-retail-0009.xml"
        reident_model_xml: "/models/face_reidentification/FP16/face-reidentification-retail-0095.xml"
        prob_threshold: 0.5
        roi_scale_factor: 1.15
        device: "AUTO"
        # device: "MYRIAD.2.1.1-ma2480"
    object_recognizer:
        yolo_model_xml: "/models/object_recognition/FP16/yolov4-tiny.xml"
        prob_threshold: 0.5
        iou_threshold: 0.4
        device: "AUTO"
        # device: "MYRIAD.2.1.4-ma2480"
vision_simulated:
    camera_frame: 'camera_link_simulation'
    camera_matrix: [ 150,  0., 320,
                      0., 150, 240,
                      0.,  0.,   1. ]
    apply_undistortion: false
    input_stream: -1
    #input_stream: "/path/to/a/video.mp4" 
    # If true node shows a window with resulting detections on the video
    show_video_result: true
    fps_lock: 30
    distance_to_camera: 0.3
    face_recognizer:
        device: "AUTO"
        detection_model_xml: "/models/face_detection/FP16/face-detection-retail-0004.xml"
        landmarks_model_xml: "/models/landmarks_regression/FP16/landmarks-regression-retail-0009.xml"
        reident_model_xml: "/models/face_reidentification/FP16/face-reidentification-retail-0095.xml"
        prob_threshold: 0.5
        roi_scale_factor: 1.15
        device: "AUTO"
        # device: "MYRIAD.2.1.1-ma2480"
    object_recognizer:
        device: "AUTO"
        yolo_model_xml: "/models/object_recognition/FP16/yolov4-tiny.xml"
        prob_threshold: 0.5
        iou_threshold: 0.4
        device: "AUTO"
        # device: "MYRIAD.2.1.1-ma2480"
