lang_model:
    lang_model_servers: {'0': 'http://ai.sweetie.bot:5000/v1/completions', '1':'http://localhost:5000/v1/completions'}
    profile:
        en:
            max_tokens: 250
            do_sample: True
            temperature: 1.3
            top_p: 0.1
            typical_p: 1
            repetition_penalty: 1.18
            top_k: 40
            no_repeat_ngram_size: 0
            penalty_alpha: 0
            seed: -1
            add_bos_token: True
            truncation_length: 2048
            ban_eos_token: False
            skip_special_tokens: True
            stop: ["\nMy emotion:", "\nHuman:", "\n"]
        ru:
            max_tokens: 250
            do_sample: True
            temperature: 1.3
            top_p: 0.1
            typical_p: 1
            repetition_penalty: 1.18
            top_k: 40
            no_repeat_ngram_size: 0
            penalty_alpha: 0
            seed: -1
            add_bos_token: True
            truncation_length: 2048
            ban_eos_token: False
            skip_special_tokens: True
            stop: ["\nМои эмоции:", "\nЧеловек:", "\n"]
        jp:
            max_tokens: 250
            do_sample: True
            temperature: 1.3
            top_p: 0.1
            typical_p: 1
            repetition_penalty: 1.18
            top_k: 40
            no_repeat_ngram_size: 0
            penalty_alpha: 0
            seed: -1
            add_bos_token: True
            truncation_length: 2048
            ban_eos_token: False
            skip_special_tokens: True
            stop: ["\n私の感情：", "\n人間：", "\n"]
