hardware:
    battery_monitor:
        period: 2.0
        sysfs_path: '/sys/class/power_supply/sbs-1-000b'
    joystick:
        sysfs_path: '/dev/input/js0'
    external_button:
        sysfs_path: '/dev/ttyUSB0'
