hardware:
    simulated:
        openmv_node:
            camera_frame: 'camera_link'
            camera_matrix: [101, 0.000000, 120, 0.000000, 101, 80, 0.000000, 0.000000, 1.000000]
            serial:
                port: '/dev/ttyACM0'
                read_timeout: 1.0
            filter:
                face:
                    length = 20
                    treshold = 7
                    alpha = 0.3
                aptil_tag:
                    length = 3
                    treshold = 2
                    alpha = 0.3
    battery_monitor:
        period: 2.0
        sysfs_path: '/sys/class/power_supply/BAT0'

