joint_state_ref:
    num_rows: 6
dynamics_visualizer:
    robot_model_namespace: "/motion"
    display_twist: true
pose_marker:
    scale: 1.0
    # IMPORTANT! Order, in which resources specifies, must
    #            correspond order, in which frames represents resources, 
    #            for proper conversion of latter to former
    resources: [ leg1, leg2, leg3, leg4, head ]
    frames: [ bone15, bone25, bone35, bone45, bone55, base_link ]
    stance_home_frame: base_link
    stance_normalized_z_level: 0.2335
    limbs_normalized_z_level: 0.03
    head_normalized_z_level: 0.3287
