voice:
    lang: 'ru,en,ja'
    sound_packages: [ sweetie_bot_sounds ]
    ladspa_path: ~/.ladspa/
    voice_profile:
        coqui-ai:
            type: 'coqui-ai'
            enabled: false
            langs: [ 'en', 'jp' ]
            coqui_ai_params:
                languages:
                    en:
                        model: 'vctk'
                        params:
                            speaker: 'p225'
                    ja:
                        model: 'kokoro'
                models:
                    vctk:
                        model_name: 'tts_models/en/vctk/vits'
                        progress_bar: false
                        gpu: false
                    kokoro:
                        model_name: 'tts_models/ja/kokoro/tacotron2-DDC'
                    ruslan:
                        model_path: 'tts_models/ru/ruslan/tacotron2-DDC.pth'
                        config_path: 'tts_models/ru/ruslan/tacotron2-DDC.json'
        rhvoice:
            type: 'rhvoice'
            enabled: true
            langs: [ 'ru' ]
            rhvoice_params:
                relative_volume:        1.0  # in percents devided by 100
                relative_rate:          0.9  # in percents devided by 100
                relative_pitch:         0.6 # in percents devided by 100
                #relative_pitch_russian: 0.60 # in percents devided by 100
                #relative_pitch_english: 0.75 # in percents devided by 100
        rhvoice_robotized:
            type: 'rhvoice'
            enabled: true
            langs: [ 'ru' ]
            rhvoice_params:
                relative_volume:        1.0  # in percents devided by 100
                relative_rate:          0.9  # in percents devided by 100
                relative_pitch:         0.6 # in percents devided by 100
            gstreamer_pipeline: 'audioconvert ! audioresample
                ! ladspa-autotalent-so-autotalent
                        concert-a="440.00"
                        fixed-pitch="0.0"
                        pull-to-fixed-pitch="0.193"
                        a="-1" ab="0" b="0" bb="-1"
                        c="0" d="-1" db="-1" e="-1"
                        eb="0" f="0" g="-1" gb="-1"
                        correction-strength="1"
                        correction-smoothness="0"
                        pitch-shift="0.2"
                        output-scale-rotate="0"
                        lfo-depth="0"
                        lfo-rate="2.29"
                        lfo-shape="0"
                        lfo-symmetry="0.2"
                        lfo-quantization="0"
                        formant-correction="1"
                        formant-warp="0.4"
                        mix="1.0"'
        speechd:
            type: 'speechd'
            enabled: true
            langs: [ 'ru', 'en' ]
            module: 'festival'
microphone:
    mic_name: "ReSpeaker 4 Mic Array"
    # mic_name: "sof-hda-dsp: - (hw:0,7)"
    # mic_name: "HD Pro Webcam C920"
    sample_rate: 16000
    supress_pyaudio_error: True
    update_rate: 4.0
    main_channel: 0
    frame_id: 'base_link'
    transcribe_servers: {'0': 'https://ai.sweetie.bot/stt/', '1':'http://localhost:8577/'}
    enable_translate: True
    key_combination: [ 'ctrl', 'alt' ,'w' ]
    debug_plot: False
    intensity_histogram_step: 100.0
    intensity_histogram_forget_factor: 0.95
    sound_intensity_threshold: 300
    intensity_normalization_divider: 2000
    doa:
        #algorithm: 'respeaker'
        algorithm: 'NormMUSIC'
        #algorithm: 'SRP'
        #algorithm: 'FRIDA'
        #algorithm: 'MUSIC'
        #algorithm: 'TOPS'
        mic_coords: [ 0.02285, -0.02285, 0.02285, 0.02285, -0.02285, 0.02285, -0.02285, -0.02285 ]
        mic_channels: [ 1, 2, 3, 4 ]
        freq_range: [ 80.0, 2000.0 ]
        mode: 'far'
        azimuth: [ -180.0, 180.0, 32 ]
        nfft: 1024
