joint_state_ref:
    num_rows: 6
dynamics_visualizer:
    robot_model_namespace: "/motion"
    display_twist: true
    balance_history_length: 1000

# Example of generic marker configuration.
#    This is old simple version of the markers system. It inteded for debugging
#    applications where new complex pose marker not appropriate.
#
# generic_pose_marker:
#     name: "Generic Pose Marker"
#     scale: 0.5
#     normalized_z_level: 0.03
#     resources: [ leg1, leg2, leg3, leg4, nose ]
#     frames: [ bone15, bone25, bone35, bone45, bone55, base_link ]
#     select_only_one_resource: true
robot_pose_marker:
    name: "Stance Pose marker"
    world_frame: odom_combined
    scale: 1.0
    normalized_z_level: 0.2335
    frame: base_link
    inner_markers:
      legs:
        list:
          leg1: { resource: leg1, frame: bone15, name: "Front-Left leg Pose marker"  }
          leg2: { resource: leg2, frame: bone25, name: "Front-Right leg Pose marker" }
          leg3: { resource: leg3, frame: bone35, name: "Hind-Left leg Pose marker"   }
          leg4: { resource: leg4, frame: bone45, name: "Hind-Right leg Pose marker"  }
        normalized_z_level: 0.03
        scale: 0.5
      limbs:
        # You can add limb marker by adding another entry in this list.
        # Markers' name fields must be different!!!
        nose:
          name: "Nose Pose marker"
          is_sphere: true
          scale: 0.5
          normalized_z_level: 0.3287
          frame: bone55
          resource: nose
          pose_topic: limb_pose
          activation_action: limb_set_operational_action
        head:
          name: "Look At marker"
          is_sphere: true
          scale: 0.5
          normalized_z_level: 0.3287
          frame: bone55
          resource: head
          pose_topic: look_at_pose
          activation_action: look_at_set_operational_action
destination_marker:
    name: "Destination marker"
    world_frame: odom_combined
    gait_generator_ns: "/gait_generator"
    scale: 1.1
    gait_type_options: [ walk_overlap, walk, trot ]
    gait_type_default_idx: 0
    n_steps_options: [ 2, 3, 4, 5 ]
    n_steps_default_idx: 2
    duration: 3.5
    nominal_height: 0.215
    recorded_trajectory_name: "recorded_trajectory"
    ee_names: [ leg1, leg2, leg3, leg4 ]
object_detection_marker:
    names: [ "Detection 1", "Detection 2" ]
    labels: [ "", "Alex", "Alice" ]
    types: [ "human", "pony", "ball" ]
    frame: odom_combined
    scale: 0.5
    nominal_height: 0.4
    max_time_lag: 0.0
    appear_duration_interval: [ 1.0, 2.0 ]
    vanish_duration_interval: [ 0.3, 1.0 ]
