KeyPressed:
    enable_group: "buttons"
    joy_topic: "joystick"
    key_topic: "keys_pressed"
    buttons:
        0: "1"
        1: "2"
        2: "3"
        3: "4"
        4: "L1"
        6: "L2"
        5: "R1"
        7: "R2"
        8: "select"
        9: "start"
    axes_positive:
        4: "left"
        5: "up"
    axes_negative:
        4: "right"
        5: "down"
JointAxes:
    enable_group: "eyes"
    joy_topic: "joystick"
    joints_topic: "eyes_joints_ref"
    buttons: { }
    axes:
        2:
            joint: "eyes_yaw"
            speed: 0.0
            min: -1.57
            max: 1.57
        3:
            joint: "eyes_pitch"
            speed: 0.0
            min: -1.57
            max: 1.57
#JointAxes:
#    enable_group: "head"
#    joy_topic: "joystick"
#    joints_topic: "head_joints_ref"
#    buttons:
#        5:
#            joint: "joint51"
#            speed: 0.4
#            min: -1.2
#            max: 0.1
#        7:
#            joint: "joint51"
#            speed: -0.4
#            min: -1.2
#            max: 0.1
#    axes:
#        0:
#            joint: "joint52"
#            speed: 0.0
#            min: -1.0
#            max: 1.0
#        1:
#            joint: "joint53"
#            speed: 0.0
#            min: -0.1
#            max: 0.6


