clop_generator:
    period: 0.056
    contact_height_tolerance: 0.005
    towr_model:
        base:
            frame_id: "base_link"
            links: ["base_link", "base_link_inertia", "bone11", "bone12", "bone21", "bone22", "bone31", "bone32", "bone41", "bone42", "bone51", "bone52", "bone53", "bone54", "screen_left", "screen_right" ]
        LF:
            name: "leg1"
            frame_id: "bone15"
            nominal_stance: [ 0.08, 0.038, -0.1675 ]
            #bounding_box: [ 0.05, 0.025, -1.2075, 0.145, 0.08, -0.1575 ]
            bounding_box: [ 0.05, 0.025, -1.2075, 1.145, 1.08, -0.1575 ]
            bounding_sphere: [ 0.08, 0.037, -0.0575, 0.17 ]
            contact_point: [ 0.0, 0.0, -0.03 ]
            links: ["bone13", "bone14", "bone15"]
        RF:
            name: "leg2"
            frame_id: "bone25"
            nominal_stance: [ 0.08, -0.038, -0.1675 ]
            #bounding_box: [ 0.05, -0.08, -1.2075, 0.145, -0.025, -0.1575 ]
            bounding_box: [ 0.05, -1.08, -1.2075, 1.145, -0.025, -0.1575 ]
            bounding_sphere: [ 0.08, -0.037, -0.0575, 0.17 ]
            contact_point: [ 0.0, 0.0, -0.03 ]
            links: ["bone23", "bone24", "bone25"]
        LH:
            name: "leg3"
            frame_id: "bone35"
            nominal_stance: [ -0.08, 0.038, -0.1675 ]
            #bounding_box: [ -0.145, 0.025, -1.2075, -0.05, 0.08, -0.1575 ]
            bounding_box: [ -1.145, 0.025, -1.2075, -0.05, 1.08, -0.1575 ]
            bounding_sphere: [ -0.08, 0.037, -0.0575, 0.17 ]
            contact_point: [ 0.0, 0.0, -0.03 ]
            links: ["bone33", "bone34", "bone35"]
        RH: 
            name: "leg4"
            frame_id: "bone45"
            nominal_stance: [ -0.08, -0.038, -0.1675 ]
            #bounding_box: [ -0.145, -0.08, -1.2075, -0.05, -0.025, -0.1575 ]
            bounding_box: [ -1.145, -1.08, -1.2075, -0.05, -0.025, -0.1575 ]
            bounding_sphere: [ -0.08, -0.037, -0.0575, 0.17 ]
            contact_point: [ 0.0, 0.0, -0.03 ]
            links: ["bone43", "bone44", "bone45"]
    towr_parameters: # see towr::Parameteres for desciption, are updated move request
        scale_per_step: false
        #duration_base_polynomial: 0.25
        #dt_constraint_dynamic: 0.25
        #dt_constraint_range_of_motion: 0.2
        #dt_constraint_base_motion: 0.0625
        duration_base_polynomial: 0.25
        dt_constraint_dynamic: 0.1
        dt_constraint_range_of_motion: 0.1
        dt_constraint_base_motion: 0.1
        ee_polynomials_per_swing_phase: 2
        optimize_phase_durations: false
        bound_phase_duration_min: 0.4
        bound_phase_duration_max: 2.0
        costs:
            base_lin_motion: 0.001
            base_ang_motion: 0.01
            ee_motion: 0.00025
    ipopt_solver_parameters:
        linear_solver: "mumps"
        jacobian_approximation: "exact"
        derivative_test: "none"  # BEWARE! Test "first-order" breaks optimization process! 
        max_cpu_time: 10.0
        print_level: 5
        max_iter: 300

