soar:
    soar_period: 1.0
    autostart: false
    agent_package: "sweetie_bot_soar"
    agent_file: "soar/walker.soar"
    input:
        rand:
            type: "rand"
        clock:
            type: "clock"
        joystick:
            type: "joystick"
            topic: "/hmi/joy_decoder/keys_pressed"
    output:
        nop: true
        textcmd: 
            topic: "control"
        flexbe:
            action_ns: "flexbe/flexbe/execute_behavior"
