lang: "en,ru"
voice_node:
    playback_command: "mpv"
    sound_packages: [ sweetie_bot_sounds ]
    # Options are: sound_play, rhvoice, rhvoice_robotized
    tts_backend: rhvoice

    # Parameters for rhvoice and rhvoice_robotized backends:
    relative_volume: 2.0 # in percents devided by 100
    relative_rate: 0.8 # in percents devided by 100

    # Parameters for rhvoice_robotized backend:
    ladspa_path: ~/.ladspa/
    java_home: /lib/jvm/adoptopenjdk-8-openj9-amd64/ # For debian
    #java_home: /lib/jvm/java-8-openjdk-amd64/ # For ubuntu
    # Next parameter is a part of gstreamer audio pipeline, that follows common beginning:
    # appsrc name=source ! audio/x-raw,format=S16LE,channels=1,rate=24000,layout=interleaved !
    robotization_pipeline: 'audioconvert ! audioresample
        ! ladspa-autotalent-so-autotalent
                concert-a="440.48001"
                fixed-pitch="0.0"
                pull-to-fixed-pitch="0.384"
                a="0" ab="1" b="0" bb="0"
                c="1" d="0" db="0" e="0"
                eb="1" f="1" g="0" gb="0"
                correction-strength="1"
                correction-smoothness="0"
                pitch-shift="-3.0"
                output-scale-rotate="5"
                lfo-depth="0.0"
                lfo-rate="10.0"
                lfo-shape="1"
                lfo-symmetry="0.032"
                lfo-quantization="0"
                formant-correction="0"
                formant-warp="-0.286"
                mix="1.0"
        ! audioconvert ! ladspa-pt-robotize-so-pt-robotize
                mode="2"
        ! autoaudiosink'

