servo_inv:
    priority: 20
    battery_voltage: 12
    lead: 0.0
    sign_dead_zone: 0.001
servo_ident:
    priority: 10
    control_delay: 0.0224
    relaxation_factor: 0.995
    error_averaging_time: 5.0
    threshold: 0.01
    battery_voltage: 12.0
    sign_dead_zone: 0.001

