default:
    kp: 100.0
    kgear: 1.0
    alpha:
        - 2.1095
        - 53.9546
        - 12.5499
        - 234.9008
servos:
    - names: [ 'joint12', 'joint13', 'joint22', 'joint23', 'joint32', 'joint33', 'joint42', 'joint43' ]
      model:
        kp: 100.0
        kgear: 1.0
        alpha:
            - 1.3887
            - 52.0818
            - 7.0933
            - 212.2978




