#! /usr/bin/env python3
import rospy
from sweetie_bot_text_msgs.msg import TextCommand
from os.path import expanduser

f = None

def callback(data):
    global f
    rospy.loginfo("%s: %s" % (data.type, data.command))
    now = rospy.get_rostime()
    f.write(f'{now.secs}.{now.nsecs};{data.type};data.command\n')

def listener():
    global f
    rospy.init_node('voice_logger', anonymous=True)
    rospy.Subscriber("voice_log", TextCommand, callback)
    now = rospy.get_rostime()
    home = expanduser("~")
    file_name = f'{home}/sweetie_bot_voice_log.{now.secs}.{now.nsecs}.log'
    rospy.loginfo(f"Wrinting log to {file_name}")
    f=open(file_name, 'a+')
    rospy.spin()

if __name__ == '__main__':
    listener()
