#!/bin/bash
TTS_PATH=$HOME/.local/share/tts
MODEL_NAME=${1:-tts_models--multilingual--multi-dataset--xtts_v2}
MODEL_FILE=${2:-model.pth}
MODEL_CONF=${3:-config.json}
MODEL_SPEAKER=${4:-speakers_xtts.pth}
MODEL_PATH=${TTS_PATH}/${MODEL_NAME}
tts-server \
	--model_path ${MODEL_PATH}/${MODEL_FILE} \
	--config_path ${MODEL_PATH}/${MODEL_CONF} \
	--speakers_file_path ${MODEL_PATH}/${MODEL_SPEAKER} \
	--use_cuda true --debug 5 --show_details 1
