#!/usr/bin/env bash
cd "$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
source $HOME/miniconda3/etc/profile.d/conda.sh
conda activate stt # change to your conda environment's name
flask run $@
