#!/usr/bin/env python

import sys, os
import rospy
from sweetie_bot_text_msgs.srv import Transcribe

def stt_client(service, filename, data):
    rospy.wait_for_service(service)
    try:
        stt_client_caller = rospy.ServiceProxy(service, Transcribe)
        resp = stt_client_caller(filename, data)
        return resp
    except rospy.ServiceException as e:
        print("Service call failed: %s"%e)

def usage():
    return "%s [-n] service filename\nExample: %s /transcribe audio.wav" % (sys.argv[0], sys.argv[0])

if __name__ == "__main__":
    if len(sys.argv) > 4 or len(sys.argv) < 3:
        print(usage())
        sys.exit(1)

    if(sys.argv[1] == "-n"):
        service  = sys.argv[2]
        filename = sys.argv[3]
        data = b""
    else:
        service  = sys.argv[1]
        filename = ""
        with open(sys.argv[2], "rb") as f:
            data = f.read()
    print(stt_client(service, filename, data))
