voice:
    lang: 'en,zh-CN'
    gender: 'female'
    gender_translation_hints:
        'female': 'She said'
        'male': 'He said'
        'unknown': 'They said'
    sound_packages: [ ]
    default_profile: 'coqui-ai'
    ladspa_path: ~/.ladspa/
    voice_profile:
        coqui-ai:
            type: 'coqui-ai'
            langs: [ 'en', 'es', 'fr', 'de', 'it', 'pt', 'pl', 'tr', 'ru', 'nl', 'cs', 'ar', 'zh-CN', 'hu', 'ko', 'ja', 'hi' ]
            enabled: true
            coqui_ai_params:
                speaker: "Asya Anara"
