herkulex:
    groups: [ all ]
    all:
        driver:
            port_name: '/dev/ttyS0'
            baudrate: 115200
        array:
            timeout: 0.060
            tryouts: 3
            activity_period: 0.057
        sched:
            priority: 40
            timeout: 0.005
            period_RT_JOG: 0.013
            period_RT_read: 0.025
            period_CM: 0.007
            detailed_state: false
            poll_list: [ joint11, joint12, joint13, joint14, joint15, joint51, joint21, joint22, joint23, joint24, joint25, joint52, joint31, joint32, joint33, joint34, joint35, joint53, joint41, joint42, joint43, joint44, joint45, joint54 ]
            poll_round_size: 6
