default:
    kp: 100.0
    kgear: 1.0
    alpha:
        - 1.3887
        - 52.0818
        - 7.0933
        - 212.2978
servos:
    - names: [ 'leg1_joint3', 'leg2_joint3' ]
      model:
        kp: 100.0
        kgear: 1.54
        alpha:
            - 1.3887
            - 52.0818
            - 7.0933
            - 212.2978
    - names: [ 'leg1_joint5', 'leg2_joint5' ]
      model:
        kp: 100.0
        kgear: 1.29
        alpha:
            - 2.1095
            - 53.9546
            - 12.5499
            - 234.9008
    - names: [ 'leg3_joint5', 'leg4_joint5' ]
      model:
        kp: 100.0
        kgear: 1.41
        alpha:
            - 2.1095
            - 53.9546
            - 12.5499
            - 234.9008
    - names: [ 'leg1_joint6', 'leg2_joint6' , 'leg3_joint2', 'leg3_joint6', 'leg4_joint2', 'leg4_joint6' ]
      model:
        kp: 100.0
        kgear: 1.0
        alpha:
            - 2.1095
            - 53.9546
            - 12.5499
            - 234.9008
    - names: [ 'head_joint1' ]
      model:
        kp: 100.0
        kgear: 2.155
        alpha:
            - 1.3887
            - 52.0818
            - 7.0933
            - 212.2978
