buttons:
    type: KeyPressed
    joy_topic: "/touch_raw"
    key_topic: "/touch"
    buttons:
        1: "nose"
        2: "forehead"
        3: "cheek_left"
        4: "temple_left"
        5: "cheek_right"
        6: "temple_right"
    axes_positive: {}
    axes_negative: {}

